### ISSUE TITLE
A question about sampling pre-train data

### ISSUE THREAD

**Issue by Today0223** [BAAI-DCAI/Bunny#10]
Hello, ask a question about data sampling.

According to the explanation in the technical report, during the second stage of sampling pretraining data, "sort the remaining samples by the cosine similarity between its text embedding and image embedding and keep samples ranking 40% - 60%". 

Why keep the portion ranked between 40% and 60%? Shouldn't the data with higher cosine similarity between text and image embeddings be considered higher quality data?

**Comment by Isaachhh** [comment]
"
We observe that clip_score top 40% is worse than rank 15%-55%, it may be led by that the image-text pairs with too high cosine similarity are "cheater", which means there exist text region in the image which is almost the caption. [Less is More: Removing Text-regions Improves CLIP Training Efficiency and Robustness](https://arxiv.org/abs/2305.05095) and [T-MARS: Improving Visual Representations by Circumventing Text Feature Learning](https://arxiv.org/abs/2307.03132) pay attention to this, too.
"
( In the last paragraph of Part 2 [here](https://github.com/BAAI-DCAI/Dataset-Pruning/tree/main/LAION) )

Here, we have tried some ranking ranges, 40%-60% works relatively well.
