### ISSUE TITLE
微调数据集制作疑问

### ISSUE THREAD

**Issue by chenzhu005774** [BAAI-DCAI/Bunny#103]
作者您好想请教一下，我想微调关注图片中的小目标内容
![a681f393bbe54a0082a858cb7f4a83a](https://github.com/BAAI-DCAI/Bunny/assets/22974327/2ddbe6f2-8183-40e7-b726-fcaf2bf3f0d3)
例如上图中的火焰。
这个时候我在制作数据集的时候 我应该是直接以大图作为微调的训练的数据集呢，还是直接切小图作为微调数据集呢。
![1720403472556](https://github.com/BAAI-DCAI/Bunny/assets/22974327/34924206-5034-4e9f-83f1-9e30352bf40a)
。

**Comment by Isaachhh** [comment]
When evaluating, which one would you use?

And you should keep the setting consistent between training and evaluating.
