### ISSUE TITLE
Encountered an error during model inference after using qwen2.

### ISSUE THREAD

**Issue by dingtine** [BAAI-DCAI/Bunny#107]
error info：
ValueError: The checkpoint you are trying to load has model type `bunny-qwen` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

in the config.json:
  "model_type": "bunny-qwen"

After merge the lora with base model, model inference with above error, how to fix it.
thanks

**Comment by Isaachhh** [comment]
https://github.com/BAAI-DCAI/Bunny/issues/39#issuecomment-2021981770

https://github.com/BAAI-DCAI/Bunny/issues/50

**Comment by dingtine** [comment]
great, it is work.
thanks!!
