### ISSUE TITLE
Question on the Role of Text Encoder in Bunny MLLM Architecture

### ISSUE THREAD

**Issue by codefanw** [BAAI-DCAI/Bunny#108]
Thanks for your impressive work! The idea of integrating a text encoder before the large language model caught my attention. Could you share the specific benefits this approach provides? Also, were any ablation studies performed to quantify the impact of this component on overall performance?

**Comment by Isaachhh** [comment]
The text encoder in our architecture figure represents for the tokenizer of LLM.
