### ISSUE TITLE
Pre_train 和 SFT

### ISSUE THREAD

**Issue by mynamelxy** [BAAI-DCAI/Bunny#109]
请问两个训练阶段分别训练和冻结哪些部分？是否可以进行改动？

**Comment by Isaachhh** [comment]
We released all of the training strategy and data of latest Bunny. Check more details about Bunny in [Technical Report](https://arxiv.org/abs/2402.11530), [Data](https://huggingface.co/datasets/BoyaWu10/Bunny-v1_1-data) and [Training Tutorial](https://github.com/BAAI-DCAI/Bunny#training-tutorial)!

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
