### ISSUE TITLE
Great work！ Does Bunny support Chinese finetune/inference?

### ISSUE THREAD

**Issue by LianghuiGuo** [BAAI-DCAI/Bunny#11]
I am wondering whether Bunny support Chinese finetune/inference?

**Comment by Isaachhh** [comment]
The Chinese ability of Bunny now is not very well due to base LLM and training data. We are improving the Chinese performance and would release soon.

If you want to finetune Bunny on Chinese data, please refer  to #7.

**Comment by LianghuiGuo** [comment]
OK, Thanks!
