### ISSUE TITLE
Download the model to local inference, but still link to huggingface.co

### ISSUE THREAD

**Issue by Kyousoso** [BAAI-DCAI/Bunny#118]
I downloaded the model to my own server and imported it like this：
![image](https://github.com/user-attachments/assets/a17f8c9e-beea-47d8-9abf-23cfe95beb3c)
But this error occurred：

File "/home/work/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 445, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to '
https://huggingface.co/
' to load this file, couldn't find it in the cached files and it looks like google/siglip-so400m-patch14-384 is not the path to a directory containing a file named config.json.

Should I modify the config. json file to solve this problem？

**Comment by Isaachhh** [comment]
https://github.com/BAAI-DCAI/Bunny/issues/55#issuecomment-2078920495

**Comment by Kyousoso** [comment]
> [#55 (comment)](https://github.com/BAAI-DCAI/Bunny/issues/55#issuecomment-2078920495)

It's working, thank you！

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
