### ISSUE TITLE
About pretrain data

### ISSUE THREAD

**Issue by kid369** [BAAI-DCAI/Bunny#119]
Great work！ I have a problem unzipping after merging the pretrian data, could you upload the whole data without spilting it?

**Comment by Isaachhh** [comment]
What is the error message?

**Comment by kid369** [comment]
tar: Skipping to next header
tar: A long zero block at 67638448
tar: Exiting with failure status due to previous errors
I got these when i tried to unzip the file

**Comment by kid369** [comment]
I will have a try, thanks very much

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
