### ISSUE TITLE
Multi-images in 1 prompt

### ISSUE THREAD

**Issue by motcapbovit** [BAAI-DCAI/Bunny#120]
Hi, thanks for your great work!

Just a little concern, since the image input is a list, can the model receive multi-images in 1 prompt for the purpose of image comparisons?

**Comment by Isaachhh** [comment]
Due to single-image training, the performance of multi-images inference would be inferior.

You may try combine several images into one and feed into the model.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
