### ISSUE TITLE
about images of pretrain data

### ISSUE THREAD

**Issue by nicedoctor** [BAAI-DCAI/Bunny#124]
I have downloaded and checked the pretrain data, however, there are only about 1/4 images of the 2M data is in the downloaded images. Where can I find the remaining images?

**Comment by Isaachhh** [comment]
It's strange because we released all the images.

Did you follow the instruction?

![image](https://github.com/user-attachments/assets/894c95f8-537e-4b95-938c-e602e2fc5783)

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
