### ISSUE TITLE
evaluation about mmbench

### ISSUE THREAD

**Issue by caiyuxuan1120** [BAAI-DCAI/Bunny#125]
Hi, thanks for your excellent work! I am wondering if either dev split or test split can be measured on https://mmbench.opencompass.org.cn/mmbench-submission? On EN_dev/CN_dev I ended up with 4330 results, is this correct?

**Comment by Isaachhh** [comment]
Yes.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
