### ISSUE TITLE
Question: What is the minimum size of an image that can be classified?

### ISSUE THREAD

**Issue by ChangGiMoon** [BAAI-DCAI/Bunny#128]
I want to use Bunny-Llama-3-8B-V to do binary classification (e.g. yes or no) on very small images. Specifically, I am going to use the cropped bounding box patch (which is the result of Object Detection) as input for Bunny-Llama-3-8B-V and verify whether the class of bounding box is correct. **Can you tell me the approximate minimum image size that can be classified?** The prompt will use the following input. The input images have various sizes and appearances as shown below.

prompt:
Based on the given image, answer the following question with 'yes' or 'no': Question: [Is there a person in this image?], Answer:

input image example:
![ex](https://github.com/user-attachments/assets/cde4a18a-39cc-46e6-9f86-a61f0c626b32)

**Comment by Isaachhh** [comment]
The input image would be resized to 448x448 for Bunny-Llama-3-8B-V.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
