### ISSUE TITLE
How to train Bunny with both image-text pair data and pure text data together? 

### ISSUE THREAD

**Issue by isjinghao** [BAAI-DCAI/Bunny#139]
How to train Bunny with both image-text pair data and pure text data together? 

Since using both of them is better for performance.

Thanks.

**Comment by Isaachhh** [comment]
We already supported it, e.g. WizardLM in Bunny-695K:

```
{'id': 'wizardlm_0', 'conversations': [{'from': 'human', 'value': 'Input a source of inspiration'}, {'from': 'gpt', 'value': 'Nature.'}]}
```

Just do not include the `image` field.

**Comment by isjinghao** [comment]
Thank you so much for your prompt reply~
