### ISSUE TITLE
model.safetensors is slow to load

### ISSUE THREAD

**Issue by carry-xz** [BAAI-DCAI/Bunny#16]
Can't wait to try, but the gradio page can't launch, what version of gradio you are using? The cli is slow to load model.safetensors

**Comment by Isaachhh** [comment]
Now the demo page can be opened. Thanks for feedback!

For slow cli loading, could you share more information? If you have downloaded the weights of lora and base llm, cli loading would be very quick.

Also, you can try the quick-starting snippet [here](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#quickstart).

**Comment by carry-xz** [comment]
git pull , it's work!
