### ISSUE TITLE
test on gradio outputs random stuff

### ISSUE THREAD

**Issue by betterftr** [BAAI-DCAI/Bunny#2]
![image](https://github.com/BAAI-DCAI/Bunny/assets/84087448/2ae0d02e-60d3-4d2f-9087-b03b085f5991)

![image](https://github.com/BAAI-DCAI/Bunny/assets/84087448/6757747d-1e9e-4c0c-b5d1-c65a13809975)

**Comment by Isaachhh** [comment]
The weights order of susnato/phi-2 **was** a concatenated qkv layer, which we use to train Bunny. However, Susnato changed them to seperate q,k,v layers to fit the latest Transformers.

Please refer to [Isaachhe/phi-2_dev](https://huggingface.co/Isaachhe/phi-2_dev/blob/main/special_tokens_map.json) other than susnato/phi-2 as base LLM to use Bunny temporarily.

Thank you so much for finding this problem! We have updated README.

We are migrating Bunny to latest Phi weights. Please wait for some time.

**Comment by Isaachhh** [comment]
Hi betterftr.

We have migrated Bunny to latest Phi weights (microsoft/phi-1_5, microsoft/phi-2) and updated weights of Bunny. Have a try!
