### ISSUE TITLE
请问支持量化推理吗？

### ISSUE THREAD

**Issue by LianghuiGuo** [BAAI-DCAI/Bunny#22]
请问可以支持量化加速推理么

**Comment by YuanJianhao508** [comment]
Hey LianghuiGuo, 谢谢你的提问！Bunny现在支持8bit推理的，用bunny/serve/cli.py的--load-8bit就可以。4bit暂时还不支持。

**Comment by LianghuiGuo** [comment]
好像，感谢解答~
