### ISSUE TITLE
What is the performance of training LLAVA by Bunny-pretrain-LAION-2M and Bunny-695K?

### ISSUE THREAD

**Issue by caopulan** [BAAI-DCAI/Bunny#25]
Have the authors conducted this ablation experiment?

**Comment by LAW1223** [comment]
Thank you for your interest, and my apologies for not exploring this option earlier. Should you wish to proceed, feel free to utilize our dataset for the training of LLaVA.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
