### ISSUE TITLE
Could u share pretrained mm_projector.bin

### ISSUE THREAD

**Issue by Jian-Lang** [BAAI-DCAI/Bunny#29]
Hello,

I attempted to instruction fine-tune the Bunny model, but found the mm_projector.bin is missing.

Would u please share ur pretrained mm_projector.bin？

Thank u for your assistance.

**Comment by Isaachhh** [comment]
training details part of [Model Zoo](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#model-zoo)

**Comment by Jian-Lang** [comment]
Thanks!
