### ISSUE TITLE
what is the performance gap between lora and full finetune

### ISSUE THREAD

**Issue by FaltingsA** [BAAI-DCAI/Bunny#30]

**Comment by Isaachhh** [comment]
Thank you for your interest.

Our early experiments found that, there exists 2 score improvement of LoRA than fully fine-tuning in MMBench dev split (64.69 vs 62.46), under certain setting.

Should you wish to proceed, feel free to try to fully fine-tuning Bunny and see the performance gap, which has been supported by our code.

**Comment by Isaachhh** [comment]
For SigLIP + Phi-2
![Screenshot 2024-03-30 at 09 50 28](https://github.com/BAAI-DCAI/Bunny/assets/93458689/1e5bb3a4-46a0-4891-9090-52634ab38630)

**Comment by FaltingsA** [comment]
Thanks for your comprehensive experimental results! We are all very interested in the effective reasons of Bunny, and it would be nice to show more ablations about data, architecture in the technical report! Thanks a lot!

**Comment by Isaachhh** [comment]
We are working on that. (:

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
