### ISSUE TITLE
Model inference speed

### ISSUE THREAD

**Issue by Alxemade** [BAAI-DCAI/Bunny#32]
hi, 
    Great work! I tried this script [huggingface-transformers](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#huggingface-transformers), but found that the inference speed is much slower than the llava series. Do you have any relevant speed tests there?

**Comment by Isaachhh** [comment]
You may install `flash_attn` and try again.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
