### ISSUE TITLE
Bunny-v1.0-2B-zh 模型有时候用英文回答问题

### ISSUE THREAD

**Issue by thesby** [BAAI-DCAI/Bunny#35]
Bunny-v1.0-2B-zh 模型有时候用英文回答问题
```
def chat(image_url, prompt):
    image = read_image(image_url)
    image_tensor = model.process_images([image], model.config).to(dtype=model.dtype)
    text = f"你是一个非常好的人工智能助手,能够非常出色的和用户交谈. USER: <image>\n{prompt} ASSISTANT:"
    text_chunks = [tokenizer(chunk).input_ids for chunk in text.split('<image>')]
    input_ids = torch.tensor(text_chunks[0] + [-200] + text_chunks[1], dtype=torch.long).unsqueeze(0)
    output_ids = model.generate(
    input_ids,
    images=image_tensor,
    max_new_tokens=100,
    use_cache=True)[0]
    return tokenizer.decode(output_ids[input_ids.shape[1]:], skip_special_tokens=True).strip()
```
是不是 Qwen2 1.8B 的对话模版不一样？

**Comment by Isaachhh** [comment]
You can try explicitly ask the model to answer in Chinese.

For example, "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{prompt}请用中文回答。 ASSISTANT:"

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
