### ISSUE TITLE
lora train question

### ISSUE THREAD

**Issue by Gary2018X** [BAAI-DCAI/Bunny#39]
Thanks for your great work!
my train sh
![image](https://github.com/BAAI-DCAI/Bunny/assets/56428019/07ada478-f62d-4f49-adb1-a23a306474c2)
why final lora config model_type is bunny-qwen? 
![image](https://github.com/BAAI-DCAI/Bunny/assets/56428019/fd9b4646-e9c1-44dd-ba51-fd325f08934c)

**Comment by Isaachhh** [comment]
https://github.com/BAAI-DCAI/Bunny/blob/main/bunny/model/language_model/bunny_qwen.py#L99

**Comment by Gary2018X** [comment]
If it's bunny_qwen, why can't I reason normally after merge_lora?

**Comment by Isaachhh** [comment]
![Screenshot 2024-03-27 at 11 20 53](https://github.com/BAAI-DCAI/Bunny/assets/93458689/70494965-6108-4878-acb3-71131640e64e)

**Comment by Gary2018X** [comment]
this is my code
python script/merge_lora_weights.py \
  	--model-path ./checkpoints-qwen1.5-1.8b/bunny-lora-qwen1.5-1.8b \
  	--model-base /root/siton-glusterfs-eaxtsxdfs/xts/models/Qwen1.5-1.8B \
  	--model-type qwen1.5-1.8b \
  	--save-model-path ./merged_model

but the final model_type still is bunny_qwen

**Comment by Isaachhh** [comment]
"but the final model_type still is bunny_qwen" is correct.

But when evaluating, you should pass `model_type = qwen1.5-1.8b`.

Please read the [README](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#cli-inference-without-gradio-interface) carefully.

"why can't I reason normally after merge_lora?" Please share the error information.

**Comment by Gary2018X** [comment]
![image](https://github.com/BAAI-DCAI/Bunny/assets/56428019/4c124740-1e51-45a6-a60b-ecab573b8ea9)

**Comment by Isaachhh** [comment]
The snippet in [Quickstart](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#quickstart) is only used for Bunny-v1.0-3B (SigLIP + Phi-2) and Bunny-v1.0-2B-zh (SigLIP + Qwen1.5-1.8B). We combine some configuration code into a single file for users' convenience. Also, you can check [`modeling_bunny_qwen2.py`](https://huggingface.co/BAAI/Bunny-v1_0-2B-zh/blob/main/modeling_bunny_qwen2.py) and [`configuration_bunny_qwen2.py`](https://huggingface.co/BAAI/Bunny-v1_0-2B-zh/blob/main/configuration_bunny_qwen2.py) and their related parts in the source code of Bunny to see the difference.

For other models including models trained by yourself, we currently only support loading them with installing source code of Bunny. Or you can copy [`modeling_bunny_qwen2.py`](https://huggingface.co/BAAI/Bunny-v1_0-2B-zh/blob/main/modeling_bunny_qwen2.py) and [`configuration_bunny_qwen2.py`](https://huggingface.co/BAAI/Bunny-v1_0-2B-zh/blob/main/configuration_bunny_qwen2.py) into your model.

**Comment by Gary2018X** [comment]
Thanks so much。

I have solved this problem
i copied  [modeling_bunny_qwen2.py](https://huggingface.co/BAAI/Bunny-v1_0-2B-zh/blob/main/modeling_bunny_qwen2.py) and [configuration_bunny_qwen2.py](https://huggingface.co/BAAI/Bunny-v1_0-2B-zh/blob/main/configuration_bunny_qwen2.py) into my model, then i changed the configs.json  model_type to bunny_qwen2 and add "auto_map": {
    "AutoConfig": "configuration_bunny_qwen2.BunnyQwen2Config",
    "AutoModelForCausalLM": "modeling_bunny_qwen2.BunnyQwen2ForCausalLM"
  },
