### ISSUE TITLE
How many hours on 8 A100 GPUs?

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [BAAI-DCAI/Bunny#41]
Hi, first of all really impressive work!

The repo states that the paper used 8 A100 GPUs for training, but can I ask how many hours training took with those GPUs?

Thank you!

**Comment by Isaachhh** [comment]
https://github.com/BAAI-DCAI/Bunny/issues/23#issuecomment-1990923334

**Comment by ryan-caesar-ramos** [comment]
Thank you!
