### ISSUE TITLE
LLaMA3 or LLaMA3-Instruct

### ISSUE THREAD

**Issue by berry-ding** [BAAI-DCAI/Bunny#47]
Great work! I want to know if your pre-training used LLaMA 3 or LLaMA 3-Instruct.

**Comment by BAAI-DCAI** [comment]
LLaMA 3 Base Model. Thanks!

**Comment by GewelsJI** [comment]
Hey, @BAAI-DCAI team,

Any experience to share what is the difference of these two versions? Why choose llama 3 base model but not instruct-tuned model?

**Comment by Isaachhh** [comment]
Our primary experiments are based on Llama-3-8B. And we then find that using instruct-tuned model would be better. Now we have updated the weights based on Llama-3-8B-Instruct.

**Comment by berry-ding** [comment]
> Our primary experiments are based on Llama-3-8B. And we then find that using instruct-tuned model would be better. Now we have updated the weights based on Llama-3-8B-Instruct.

Great news! Looking forward to your release of the fine-tuning strategies.

**Comment by GewelsJI** [comment]
That's awesome. Keep attention on your updates. Thanks.

**Comment by GewelsJI** [comment]
@Isaachhh 

Further question is: do you guys wanna play with Gemma models in your codebase?

**Comment by Isaachhh** [comment]
@GewelsJI
Hi, we conducted some experiments about Bunny-Gemma on mid March and I uploaded the related codes into `gemma_temp` branch. Note that the `version` and `conv_mode` should be `gemma`.

But we can't guarantee that it works well now. And we may not release the model weights recently.

Hope this can help me. Feel free to comment if you have further questions.

**Comment by galleon** [comment]
@Isaachhh 
I would like to fine tune Bunny-Llama-3-8B-V on some of my data. Can I use the existing `train.py` file or should I wait for better VIT strategy you mentioned in the README.md

thanks for your work

**Comment by galleon** [comment]
I [think] was able to finetune the adapter starting from [phi2 pretrain weights](https://huggingface.co/BAAI/bunny-pretrain-phi-2-siglip). Any plan to release those weights for phi3 and llama3 ?

**Comment by Isaachhh** [comment]
@galleon 

We have released that.

**Comment by galleon** [comment]
@IsaachhhI was not able to find them on 🤗. I am talking abt this BAAI/bunny-pretrain-phi-2-siglip but for phi-3 or llama3 … May be it can be extracted from the full model ? How ?Sent from a small deviceOn 8 May 2024, at 14:50, Isaachhh ***@***.***> wrote:﻿
@galleon
We have released that.

**Comment by Isaachhh** [comment]
@galleon 

Training details of [model zoo](https://github.com/BAAI-DCAI/Bunny)
<img width="839" alt="Screenshot 2024-05-08 at 22 00 13" src="https://github.com/BAAI-DCAI/Bunny/assets/93458689/0b779dad-5f98-48b4-ae0d-28bc8a1885ff">

**Comment by galleon** [comment]
Thanks for adding that !Sent from a small deviceOn 8 May 2024, at 16:01, Isaachhh ***@***.***> wrote:﻿
@galleon
Training details of model zoo
Screenshot.2024-05-08.at.22.00.13.png (view on web)

**Comment by berry-ding** [comment]
@Isaachhh hi master, do you have any plan to release the high resolution LLaMA3-based model ?

**Comment by Isaachhh** [comment]
@berry-ding Thanks for interest. In following weeks, stay tuned!

**Comment by Isaachhh** [comment]
@berry-ding Hi, we released [Bunny-v1.1-Llama-3-8B-V](https://huggingface.co/BAAI/Bunny-v1_1-Llama-3-8B-V) supporting 1152x1152.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
