### ISSUE TITLE
啥时候支持下ollama方便部署测试

### ISSUE THREAD

**Issue by yuanjie-ai** [BAAI-DCAI/Bunny#48]
啥时候支持下ollama方便部署测试

**Comment by clstech** [comment]
+1

**Comment by RussRobin** [comment]
Hi @yuanjie-ai  & @clstech , thanks for reaching out.

Supports for **ollama** are in our schedule, but not top priority. We are not sure when it will be released. You are very welcome to start a pull request for it if you've done so!

Sorry for all the delays and millions of thanks for you interest in implementing our work. Stay tuned.

Regards
Russell
BAAI

**Comment by seasoncool** [comment]
+1

**Comment by Isaachhh** [comment]
Hi! We released GGUF [here](https://huggingface.co/BoyaWu10/Bunny-Llama-3-8B-V-gguf).
