### ISSUE TITLE
Request for clarification on training strategy for bunny-llama-3-8b-v

### ISSUE THREAD

**Issue by slchenchn** [BAAI-DCAI/Bunny#54]
Hello,

I noticed in the README that it mentions, "We use a better strategy to train Bunny-Llama-3-8B-V, which will be open-sourced soon!" Could you briefly describe this better strategy?

Thank you!

**Comment by RussRobin** [comment]
Hi @slchenchn, thank you for your interest in our work.

We are super busy these days but the traing strategy is scheduled to be released. Stay tuned. 

Regards
Russell
BAAI

**Comment by Isaachhh** [comment]
@slchenchn We released all of the training strategy and data of latest Bunny. Check more details about Bunny in [Technical Report](https://arxiv.org/abs/2402.11530), [Data](https://huggingface.co/datasets/BoyaWu10/Bunny-v1_1-data) and [Training Tutorial](https://github.com/BAAI-DCAI/Bunny#training-tutorial)!
