### ISSUE TITLE
run worker error

### ISSUE THREAD

**Issue by chenzhu005774** [BAAI-DCAI/Bunny#55]
root@ubuntu-Z690:/mnt/workspace/.cache/modelscope/BAAI/Bunny-v1___0-3B# python -m bunny.serve.model_worker   --host 0.0.0.0   --controller http://localhost:10000   --port 40000   --worker http://localhost:40000   --model-path /mnt/workspace/.cache/modelscope/BAAI/

2024-04-26 11:49:04.450276: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-26 11:49:04.451693: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-26 11:49:04.469047: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-26 11:49:04.469064: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-26 11:49:04.469078: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-26 11:49:04.472914: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-26 11:49:04.473033: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-26 11:49:04.905731: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Bunny/bunny/serve/model_worker.py", line 20, in <module>
    from bunny.model.builder import load_pretrained_model
  File "/Bunny/bunny/model/__init__.py", line 1, in <module>
    from .language_model.bunny_phi import BunnyPhiForCausalLM, BunnyPhiConfig
  File "/Bunny/bunny/model/language_model/bunny_phi.py", line 11, in <module>
    from ..bunny_arch import BunnyMetaModel, BunnyMetaForCausalLM
  File "/Bunny/bunny/model/bunny_arch.py", line 6, in <module>
    from .multimodal_projector.builder import build_vision_projector
  File "/Bunny/bunny/model/multimodal_projector/builder.py", line 5, in <module>
    from timm.layers.norm_act import LayerNormAct2d
ModuleNotFoundError: No module named 'timm.layers'

**Comment by Isaachhh** [comment]
Have you done [Installation](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#install)?

**Comment by chenzhu005774** [comment]
> Have you done [Installation](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#install)?

Yes, installation is complete。I started it in the modelscope container, And I start 'python -m bunny.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload --share 'and' python -m bunny.serve.controller --host 0.0.0.0 --port 10000 'are started normally. My cuda environment is also normal.
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/3218561c-146c-44b0-a5f3-1cc7112ca4b5)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/d44fa19f-b4bf-465d-ac14-cfcc5d4f122c)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/c7463826-4fc4-4ec1-ab07-14aee9a68492)

Thanks!!

**Comment by chenzhu005774** [comment]
> > Have you done [Installation](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#install)?
> 
> Yes, installation is complete。I started it in the modelscope container, And I start 'python -m bunny.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload --share 'and' python -m bunny.serve.controller --host 0.0.0.0 --port 10000 'are started normally. My cuda environment is also normal. ![image](https://private-user-images.githubusercontent.com/22974327/325849043-3218561c-146c-44b0-a5f3-1cc7112ca4b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDY0OTgsIm5iZiI6MTcxNDEwNjE5OCwicGF0aCI6Ii8yMjk3NDMyNy8zMjU4NDkwNDMtMzIxODU2MWMtMTQ2Yy00NGIwLWE1ZjMtMWNjNzExMmNhNGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA0MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkY2ZlZTI3MmFkZWEwMWVhMmU4Yzk5YzQ5NWFiMDljMTVjNGQ4MmU4ZDQ4MzRlNjNjMzIwMzQ5Mzc3NmMwZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9FIHOrnm5DlFTsLScFW2wK77ONZAZYAO-HR9O0GuIIc) ![image](https://private-user-images.githubusercontent.com/22974327/325849120-d44fa19f-b4bf-465d-ac14-cfcc5d4f122c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDY0OTgsIm5iZiI6MTcxNDEwNjE5OCwicGF0aCI6Ii8yMjk3NDMyNy8zMjU4NDkxMjAtZDQ0ZmExOWYtYjRiZi00NjVkLWFjMTQtY2ZjYzVkNGYxMjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA0MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YmVlMWI5YjRkNmZkYjA1N2M3NmFhNGM1ZjkyYzFmOWE5NWEyODQ4Y2VkMWNjNDZlNTQ2ZmRiOGQ3M2QwNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lzLoOYY4X3dSTUQtD92BNNXxH9_sV-uvBsimUZs5bDI) ![image](https://private-user-images.githubusercontent.com/22974327/325849191-c7463826-4fc4-4ec1-ab07-14aee9a68492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDY0OTgsIm5iZiI6MTcxNDEwNjE5OCwicGF0aCI6Ii8yMjk3NDMyNy8zMjU4NDkxOTEtYzc0NjM4MjYtNGZjNC00ZWMxLWFiMDctMTRhZWU5YTY4NDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA0MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NWQ0MzFmMDU3NTZjMDljZmQ1NDgzNzUwNmRlYTdhODMwNTYzMjAyYzNkMjc1ZmIyNGY4ZGI4ODE4NDQxMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uLyqzO0JzRDGs1Fd5qTSN_5lyjE0v3v14ygoFN2GLcI)
> 
> Thanks!!

and this is my docker images info:docker run --name bunny --gpus all -it -p 10000:10000 7860:7860 --network host registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.12.0 bash

**Comment by Isaachhh** [comment]
may be the `timm` version? We use `0.9.16`.

**Comment by chenzhu005774** [comment]
> may be the `timm` version? We use `0.9.16`.

It didn't work, I use the registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.12.0 'The mirror image should be fine

**Comment by chenzhu005774** [comment]
> may be the `timm` version? We use `0.9.16`.

Or can I ship a docker image of a full environment

**Comment by Isaachhh** [comment]
Well, I notice that there are some tensorflow errors, which is strange:

2024-04-26 11:49:04.469047: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-26 11:49:04.469064: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-26 11:49:04.469078: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

BTW, it shoule be `python -m bunny.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000/ --port 40000 --worker http://localhost:40000/ --model-path /mnt/workspace/.cache/modelscope/BAAI/Bunny-v1___0-3B --model-type phi-2`

**Comment by chenzhu005774** [comment]
> Well, I notice that there are some tensorflow errors, which is strange:
> 
> 2024-04-26 11:49:04.469047: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered 2024-04-26 11:49:04.469064: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered 2024-04-26 11:49:04.469078: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> 
> BTW, it shoule be `python -m bunny.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000/ --port 40000 --worker http://localhost:40000/ --model-path /mnt/workspace/.cache/modelscope/BAAI/Bunny-v1___0-3B --model-type phi-2`

So can you release a docker image of a complete environment? Thank you

**Comment by RussRobin** [comment]
Hi @chenzhu005774 , thank you for your interest in our work.

Please try our docker: `docker pull russellrobin/bunny:latest`. You may also want to refer to [Installation](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#install) and update local codes in our docker.

Regards
Russell
BAAI

**Comment by chenzhu005774** [comment]
> docker pull russellrobin/bunny:latest

Thank you. I'll try.

**Comment by chenzhu005774** [comment]
> Hi @chenzhu005774 , thank you for your interest in our work.
> 
> Please try our docker: `docker pull russellrobin/bunny:latest`. You may also want to refer to [Installation](https://github.com/BAAI-DCAI/Bunny?tab=readme-ov-file#install) and update local codes in our docker.
> 
> Regards Russell BAAI

Thank you the environment should be usable. But I couldn't download the model online due to network problems. So I put I manually download good model in the ". / root/cache/huggingface/" directory, Then run the python -m bunny.serve.model_worker --host 0.0.0.0 --controller http://:10001 --port 40000 --worker http://localhost:40000 --model-path BAAI/Bunny-v1_0-3B --model-type phi-2 "Let me download it. So I would like to ask how to load the locally downloaded model

**Comment by Isaachhh** [comment]
1. `--model-path` points to the **absolute** path
2. change `mm_vision_tower` to the absolute path of siglip in `config.json` in `Bunny-v1.0-3B`

**Comment by chenzhu005774** [comment]
> 2\. mm_vision_tower
Yes I am the absolute path，but I still have to download
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/6218e998-fbbd-44bd-b19e-dbebed5ae49f)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/19ce064e-7f2e-4f3a-873d-dedc72e9eeb7)

**Comment by chenzhu005774** [comment]
> 1. `--model-path` points to the **absolute** path
> 2. change `mm_vision_tower` to the absolute path of siglip in `config.json` in `Bunny-v1.0-3B`

![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/ec45767e-02b3-4574-9006-410cfb9deb7d)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/fb7af77f-d9e8-4577-adaa-5186fd02cb14)
So what parameters should the version use here .Thanks

**Comment by chenzhu005774** [comment]
> change mm_vision_tower to **the absolute path of siglip** in config.json in Bunny-v1.0-3B

I'm sorry, but I understand where are mm_vision_tower, config.json and Bunny-v1.0-3B respectively
