### ISSUE TITLE
模型无法理解用户输入了多少张图片

### ISSUE THREAD

**Issue by CanvaChen** [BAAI-DCAI/Bunny#56]
![image](https://github.com/BAAI-DCAI/Bunny/assets/18375123/86fbf2e5-801a-4266-8fdd-64b8f0c7acd2)
如图，我选了一张图片，回答说3张。

**Comment by RussRobin** [comment]
Hi @CanvaChen , thank you for trying our model out and this interesting failure case.

Currently in our training set, such QAs are not included. Our pretrain and fine-tune dataset include no more than 1  image as input. Our questions didn't ask the model to count number of input images. Again, this is a super interesting failure case, and thank you very much for sharing it!

Regards
Russell
BAAI
