### ISSUE TITLE
Quick start The demo running time is abnormal

### ISSUE THREAD

**Issue by chenzhu005774** [BAAI-DCAI/Bunny#59]
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/1152c9fe-2542-46e2-9153-602dd24495e5)
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/cef7b4b2-3ad7-4123-9c99-a6c0eebc4d60)
I used a fast-start demo that took 30 seconds to complete on a 4090Ti.
![image](https://github.com/BAAI-DCAI/Bunny/assets/22974327/a9f47769-23da-441b-9a5d-d2515368bdd8)
But I use the web service interface processing time only needs 200ms, read the code, the core reasoning method and parameters are basically the same, could you tell me why, thank you

**Comment by RussRobin** [comment]
Hi @chenzhu005774 , thank you for your interest in Bunny.

I tried it on 16G 4060Ti:
if `torch.set_default_device('cpu')`, 6s for `model = AutoModelForCausalLM` & `tokenizer = AutoTokenizer`, 13s for all other things. If you generate for more than 1 time in quick start, 10s for every following generations.

If` torch.set_default_device('cuda')`, and `.cuda()` for `input_ids `& `image_tensor`: around 1.2~1.4s for second and third generation.

Hope this helps!

Regards
Russell 
BAAI
