### ISSUE TITLE
Bunny-Llama-3-8B-V

### ISSUE THREAD

**Issue by believewhat** [BAAI-DCAI/Bunny#60]
I directly used the code from huggingface to generate the answer. But got some starnge symbols such as: !!!!!!!!!!!!

Could you please help me?

**Comment by Isaachhh** [comment]
Could you please show us more information about your image and text prompt?

**Comment by believewhat** [comment]
> Could you please show us more information about your image and text prompt?

Text prompt come from the example which post on huggingface:

prompt = 'Why is the image funny?'
text = f"A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: <image>\n{prompt} ASSISTANT:"

Image is the icon.png

**Comment by Isaachhh** [comment]
I tried and got

> The image is funny because it depicts a rabbit, which is not typically associated with technology or space travel, using a laptop and wearing a space suit. This juxtaposition of a cute, domestic animal in a futuristic setting creates a humorous contrast.

You may `git pull` to make sure your Bunny-Llama-3-8B-V weights are up-to-date.

**Comment by believewhat** [comment]
> I tried and got
> 
> > The image is funny because it depicts a rabbit, which is not typically associated with technology or space travel, using a laptop and wearing a space suit. This juxtaposition of a cute, domestic animal in a futuristic setting creates a humorous contrast.
> 
> You may `git pull` to make sure your Bunny-Llama-3-8B-V weights are up-to-date.

![1714361712904](https://github.com/BAAI-DCAI/Bunny/assets/38290688/f11d7f01-7cc4-40ba-8456-0d1ddcda692d)

I think my model's weights are up-to-date. But I still got this output: "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

**Comment by believewhat** [comment]
> > I tried and got
> > > The image is funny because it depicts a rabbit, which is not typically associated with technology or space travel, using a laptop and wearing a space suit. This juxtaposition of a cute, domestic animal in a futuristic setting creates a humorous contrast.
> > 
> > 
> > You may `git pull` to make sure your Bunny-Llama-3-8B-V weights are up-to-date.
> 
> ![1714361819511](https://private-user-images.githubusercontent.com/38290688/326324424-ac9b814c-0f04-4d3a-bb82-b056562fe315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjIxMzQsIm5iZiI6MTcxNDM2MTgzNCwicGF0aCI6Ii8zODI5MDY4OC8zMjYzMjQ0MjQtYWM5YjgxNGMtMGYwNC00ZDNhLWJiODItYjA1NjU2MmZlMzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAzMzcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZTYzZDVhOGUwYTM0OGFkOTg0YTc3Yzk1MGRmZGMyMzVjYTc4YjQwMWI5NDA5MzY5YTM3NGE3MjcxZTM3YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LysjG1YquOngIcE9ZQ04yf1JHiFaLtUqWjACMRm_kV8)
> 
> I think my model's weights are up-to-date. But I still got this output: "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

**Comment by believewhat** [comment]
> I tried and got
> 
> > The image is funny because it depicts a rabbit, which is not typically associated with technology or space travel, using a laptop and wearing a space suit. This juxtaposition of a cute, domestic animal in a futuristic setting creates a humorous contrast.
> 
> You may `git pull` to make sure your Bunny-Llama-3-8B-V weights are up-to-date.

I also want to confirm that whether we are using the same code: https://huggingface.co/BAAI/Bunny-Llama-3-8B-V and I didn't use repo id to load the model.

**Comment by Isaachhh** [comment]
> Could you please upload your requirement.txt? Thank you very much.

I just `pip install torch transformers accelerate pillow` and I use the code in our model page.

You may uncomment the "disable some warnings" part to see whether there are any warnings.

And you may print the `input_ids` to see whether the tokenizer works well.

**Comment by believewhat** [comment]
> > Could you please upload your requirement.txt? Thank you very much.
> 
> I just `pip install torch transformers accelerate pillow` and I use the code in our model page.
> 
> You may uncomment the "disable some warnings" part to see whether there are any warnings.
> 
> And you may print the `input_ids` to see whether the tokenizer works well.

I only got this warning:
warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/jwang/anaconda3/envs/bunny/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.head.mlp.fc2.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)

For input_ids:
![1714397306660](https://github.com/BAAI-DCAI/Bunny/assets/38290688/c5de13aa-3d9a-4798-afc2-f99f673e55c2)

I guess decoder function could work well?

**Comment by believewhat** [comment]
I found that if I do inference on A100, it could work.... But if I do inference on H100, it doesn't work... strange

**Comment by Isaachhh** [comment]
> I found that if I do inference on A100, it could work.... But if I do inference on H100, it doesn't work... strange

What if you try `dtype=torch.bfloat16` on H100?

**Comment by believewhat** [comment]
I tried but it doesn't work. But that's ok, I could use other gpu to inference. Thank you very much.
