### ISSUE TITLE
請問可以在MacBook M系列的電腦上跑嗎？

### ISSUE THREAD

**Issue by seasoncool** [BAAI-DCAI/Bunny#61]
我看到有個配置 只有cpu 和cuda的選項，不確定能否支持Macbook的GPU來使用。

**Comment by LAW1223** [comment]
目前我們還不支持 MacBook GPU来使用，但我們將會在未來進行探索。請留意我們的進展。謝謝您的關注！
We currently do not support the use of MacBook GPU, but we will explore this possibility in the future. Please stay tuned for updates. Thank you for your attention!

**Comment by Isaachhh** [comment]
Hi! We released GGUF [here](https://huggingface.co/BoyaWu10/Bunny-Llama-3-8B-V-gguf). Try it with ollama running on Mac.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
