### ISSUE TITLE
Do you plan to train the vlm using llama3 70b instruct？

### ISSUE THREAD

**Issue by Alethx** [BAAI-DCAI/Bunny#65]

**Comment by ChaseKolozsy** [comment]
> Hi Alethx, thanks for the question. We currently focus on lightweight MLLMs and don't plan to train with Llama3-70B.

I was thinking about merging your bunny-llama3-8b-V model with llama3-70b, do you think that would work? or is it a waste of time and money?

**Comment by Isaachhh** [comment]
Well, probably not working.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
