### ISSUE TITLE
Is the llama3-v model input resolution is 384?

### ISSUE THREAD

**Issue by lucasjinreal** [BAAI-DCAI/Bunny#67]
Is the llama3-v model input resolution is 384?

**Comment by Isaachhh** [comment]
Yes.

**Comment by lucasjinreal** [comment]
Why didn't consider enlarge the input size?

**Comment by lucasjinreal** [comment]
It it s2 version?

**Comment by Isaachhh** [comment]
Yes.

**Comment by lucasjinreal** [comment]
@Isaachhh  Hi, does llama3 is full model finetune or lora?

**Comment by Isaachhh** [comment]
LoRA.

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.

**Comment by zezeze97** [comment]
使用S2训练和推理是不是相比不使用，速度慢很多
