### ISSUE TITLE
DINOv2 和 SigLIP 融合

### ISSUE THREAD

**Issue by CanvaChen** [BAAI-DCAI/Bunny#77]
有模型采用 DINOv2 和 SigLIP 融合的视觉表征，通过将两个视觉编码器的输出拼接在一起送入投影器，模型能够更好的捕捉到 SigLIP 带来的高层次的语义特征和 DINOv2 提取的低层次的细粒度图像特征。
![image](https://github.com/BAAI-DCAI/Bunny/assets/18375123/b3cc324c-018e-40b4-9d86-c49bf9d0c3e3)
有试过这样是否能使Bunny效果更好吗？

**Comment by Isaachhh** [comment]
Thank you for your interest, and my apologies for not exploring this strategy. Should you wish to proceed, feel free to try to combine multiple vision towers.
