### ISSUE TITLE
Release for Bunny-Llama3 LoRA Weights

### ISSUE THREAD

**Issue by cjfcsjt** [BAAI-DCAI/Bunny#81]
Thank you for your work. When will the bunny-llama3 LoRA weights be released?

**Comment by Isaachhh** [comment]
We decided not to release the LoRA weights of Phi-3 and Llama-3-based Bunny.

But we released all of he training strategy and data of latest Bunny. Check more details about Bunny in [Technical Report](https://arxiv.org/abs/2402.11530), [Data](https://huggingface.co/datasets/BoyaWu10/Bunny-v1_1-data) and [Training Tutorial](https://github.com/BAAI-DCAI/Bunny#training-tutorial)!

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
