### ISSUE TITLE
Please add detailed steps on How to convert the Bunny Family of Models to GGUF?

### ISSUE THREAD

**Issue by criminact** [BAAI-DCAI/Bunny#85]
I have tried converting the Bunny model to GGUF using the script - https://github.com/ggerganov/llama.cpp/tree/master/examples/llava (Right now the script is only available for Llava1.5 and 1.6, Moondream & MiniCPM). Please add your conversion script so it can be consumed on edge devices.

**Comment by Isaachhh** [comment]
We have released the GGUF format of Bunny-v1.0-4B and Bunny-Llama-3-8B-V.

**Comment by criminact** [comment]
@Isaachhh Right. But we would need the steps how you're converting the model to GGUF since we have FT your vanilla Bunny model and want to consume it on edge devices using LLama.cpp

**Comment by criminact** [comment]
#80 Saw this that Llama.cpp doesn't support S2 wrapper yet. But I think this was implemented since Moondream uses SigLip and it works for that model. 

Please let me know if you need any help form our side. Having a detailed set of steps to convert a FT bunny model to GGUF would do wonders for us. Thanks in advance.

**Comment by Isaachhh** [comment]
Llama.cpp supports SigLIP, so we released the GGUF format of Bunny-v1.0-4B and Bunny-Llama-3-8B-V.

Llama.cpp doesn't support S2-Wrapper, so we didn't release the GGUF format of Bunny-v1.1-4B.

For the conversion, there is no trouble because I myself convert Bunny-v1.0-4B and Bunny-Llama-3-8B-V to GGUF format. But I am too busy these days to release an instrcution. I would try my best ASAP.

**Comment by criminact** [comment]
Cool @Isaachhh. It would be a great help if you could release the script you use to convert the **Bunny-v1.0-4B and Bunny-Llama-3-8B-V** models to GGUF. I can put up a set of instructions myself using that script in the documentation.

**Comment by puffanddmx** [comment]
Me too
Can you share instruction to convert this into GGUF if possible?

**Comment by puffanddmx** [comment]
can you let me know how to convert this into Q5_K_M GGUF format ? 
BAAI/Bunny-Llama-3-8B-V this version.

The way how to convert this ? i want to create myself to create gguf based on it.

**Comment by Isaachhh** [comment]
https://github.com/BAAI-DCAI/Bunny/blob/main/script/conversion_to_GGUF.md

**Comment by Isaachhh** [comment]
@puffanddmx

Just download [Bunny-Llama-3-8B-V-gguf](https://huggingface.co/BAAI/Bunny-Llama-3-8B-V-gguf) and quantize the `gguf` files using `llama.cpp`.

e.g. `./quantize Bunny-Llama-3-8B-V-gguf/ggml-model-f16.gguf Bunny-Llama-3-8B-V-gguf/ggml-model-Q5_K_M.gguf Q5_K_M`

**Comment by puffanddmx** [comment]
MacBook-Pro-2 gguf % ./llama.cpp/bin/quantize Bunny/mmproj-model-f16.gguf Bunny/ggml-model-Q5_K_M.gguf Q5_K_M
main: build = 3053 (0541f062)
main: built with Apple clang version 15.0.0 (clang-1500.3.9.4) for arm64-apple-darwin23.4.0
main: quantizing 'Bunny/mmproj-model-f16.gguf' to 'Bunny/ggml-model-Q5_K_M.gguf' as Q5_K_M
llama_model_loader: loaded meta data with 22 key-value pairs and 434 tensors from Bunny/mmproj-model-f16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = clip
llama_model_loader: - kv   1:                      clip.has_text_encoder bool             = false
llama_model_loader: - kv   2:                    clip.has_vision_encoder bool             = true
llama_model_loader: - kv   3:                   clip.has_llava_projector bool             = true
llama_model_loader: - kv   4:                          general.file_type u32              = 1
llama_model_loader: - kv   5:                               general.name str              = BAAI/Bunny-Llama-3-8B-V
llama_model_loader: - kv   6:                        general.description str              = image encoder for LLaVA
llama_model_loader: - kv   7:                        clip.projector_type str              = mlp
llama_model_loader: - kv   8:                     clip.vision.image_size u32              = 384
llama_model_loader: - kv   9:                     clip.vision.patch_size u32              = 14
llama_model_loader: - kv  10:               clip.vision.embedding_length u32              = 1152
llama_model_loader: - kv  11:            clip.vision.feed_forward_length u32              = 4304
llama_model_loader: - kv  12:                 clip.vision.projection_dim u32              = 1152
llama_model_loader: - kv  13:           clip.vision.attention.head_count u32              = 16
llama_model_loader: - kv  14:   clip.vision.attention.layer_norm_epsilon f32              = 0.000001
llama_model_loader: - kv  15:                    clip.vision.block_count u32              = 26
llama_model_loader: - kv  16:          clip.vision.image_crop_resolution u32              = 384
llama_model_loader: - kv  17:             clip.vision.image_aspect_ratio str              = pad
llama_model_loader: - kv  18:              clip.vision.mm_projector_type str              = mlp2x_gelu
llama_model_loader: - kv  19:                     clip.vision.image_mean arr[f32,3]       = [0.500000, 0.500000, 0.500000]
llama_model_loader: - kv  20:                      clip.vision.image_std arr[f32,3]       = [0.500000, 0.500000, 0.500000]
llama_model_loader: - kv  21:                              clip.use_gelu bool             = false
llama_model_loader: - type  f32:  271 tensors
llama_model_loader: - type  f16:  163 tensors
llama_model_quantize: failed to quantize: unknown model architecture: 'clip'
main: failed to quantize model from 'Bunny/mmproj-model-f16.gguf'

**Comment by Isaachhh** [comment]
@puffanddmx I think you can only quantize the language part (ggml-model-f16.gguf).

**Comment by puffanddmx** [comment]
i try , let you know the result
