### ISSUE TITLE
why use deepspeed zero2 for pretrain but use zero3 for finetune?

### ISSUE THREAD

**Issue by double-fire-0** [BAAI-DCAI/Bunny#91]
Are there any other considerations besides saving GPU memory?

**Comment by Isaachhh** [comment]
It's from LLaVA.

BTW, the [pretrain](https://huggingface.co/BoyaWu10/bunny-pretrain-llama3-8b-siglip-s2) stage of Bunny-v1.1-Llama-3-8B-V is under zero3.

**Comment by double-fire-0** [comment]
thx
