### ISSUE TITLE
修改或融合视觉模块

### ISSUE THREAD

**Issue by Why0912** [BAAI-DCAI/Bunny#99]
请问是否支持修改视觉模块或融合多个主干的视觉表征？
如果进行修改或融合，是否需要重新进行pre_train来获得相应的projector权重？
或是如何对projector进行修改？

**Comment by Isaachhh** [comment]
For another vision tower or projector, you can import what you like. Pay attention to [multimodal_encoder](https://github.com/BAAI-DCAI/Bunny/tree/main/bunny/model/multimodal_encoder) and [multimodal_projector](https://github.com/BAAI-DCAI/Bunny/tree/main/bunny/model/multimodal_projector). You need to add the code of class and modify the `build` function.

For combining multiple vision features, you also need to modify the [architecture](https://github.com/BAAI-DCAI/Bunny/blob/main/bunny/model/bunny_arch.py#L11) of Bunny (something like vision_tower_list) and [`encode_image`](https://github.com/BAAI-DCAI/Bunny/blob/main/bunny/model/bunny_arch.py#L71)  function and etc.

Generally, you need to pre-train and fine-tune by yourself. Under some circumstances, you may start from our released weights.

**Comment by Why0912** [comment]
感谢回复，另外问一下pre_train大概需要怎样的算力资源？

**Comment by Isaachhh** [comment]
https://github.com/BAAI-DCAI/Bunny/issues/90

**Comment by Isaachhh** [comment]
Close the issue for now if there's no further discussions. Feel free to reopen it if there's any other questions.
